<?php

namespace AppBundle\Repository;

/**
 * AdminpayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminpayRepository extends \Doctrine\ORM\EntityRepository
{
}
