admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

annonce:
    resource: "@AnnonceBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /optional_routing_prefix
    
mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications